Welcome to BITS Pialni DevOps Course! Continuous Integration is successful....
Continuous Delivery is successful....! Yuppee its working awesome!!!
Accomadating every Push changes!! Testing successful!!!
